"""empty message

Revision ID: 5fd5279bf023
Revises: 
Create Date: 2024-12-24 17:09:31.628898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd5279bf023'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Emisi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emisi_name', sa.String(length=128), nullable=False),
    sa.Column('emisi_desc', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emisi_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Emisi')
    op.drop_table('Account')
    # ### end Alembic commands ###
