"""empty message

Revision ID: 8ebbda3b1e2f
Revises: 
Create Date: 2024-12-24 17:27:41.336107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ebbda3b1e2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('emisi', schema=None) as batch_op:
        batch_op.drop_index('emisi_name')

    op.drop_table('emisi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emisi',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('emisi_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('emisi_desc', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('emisi', schema=None) as batch_op:
        batch_op.create_index('emisi_name', ['emisi_name'], unique=True)

    op.drop_table('Account')
    # ### end Alembic commands ###
