"""empty message

Revision ID: b4301c03e06b
Revises: 
Create Date: 2024-12-17 18:40:58.735745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4301c03e06b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('CategoryEmisi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.Column('category_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Emisi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emisi_name', sa.String(length=80), nullable=False),
    sa.Column('emisi_desc', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emisi_desc'),
    sa.UniqueConstraint('emisi_name')
    )
    op.create_table('Total',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_name', sa.String(length=50), nullable=False),
    sa.Column('total_emisi', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Wilayah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wilayah_name', sa.String(length=50), nullable=False),
    sa.Column('wilayah_emisi', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Wilayah')
    op.drop_table('Total')
    op.drop_table('Emisi')
    op.drop_table('CategoryEmisi')
    op.drop_table('Account')
    # ### end Alembic commands ###
